language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: j59bn0OSDhBya0ZO2enq7d7eWrp505tLRTzp4mE6K7cSAg4kD0osFkP6K3WucAZUNp6blvGD4GO3NTb8FmTktnvG7IHRYW2pUVXb2C8zZQIWhekOqfPyBApYad52CvmD+40DNYal2bvgfjCID88DGm61NZDrFMljx9Y3GyBPgeDanOH71jIz5Lo6YfrFq6BfFJfV8jpqsiF26ntU10SDG+daC34C4x1BX+sQ3Nubw5Dy39VJZuub0WT7pTbgdOccspI/68+M5uj/LKjVwy7uJtG1d992Bx0A/Iqcbvy3KsiTOylAFg1xswRx9BA/Xs0vh9kWOHWY2y0YOBzknCTQCU9Am+Hgm4npDg/wnJ7f12v91+KT9KFbUUX/eq1Wa4HEb+Hj0upuRUc8wuKzqbJPHvHdAJdSA8ai6UKgyVYmjyKAA0UnyNaEhQ47rV1RGz6wm4T1CkFPdYYW0C9n6kSfMxOkn+mF7fq+uOLU/kU5nZL+nX/Fc7/ka/koGQPqkYd0MSlKqXw0p+jOMGUBpro5os58StJLM1/4Kos7OTwAVvRF6Vq6lQOaGZ+LtuxHNeYcz7+IpWHYVr11xO0LCVeht72z9i51HROkVob/9xNKnIaV9otZ/0DCMmIwt+cVVyE/WYL4qiomVPv0IXzdVNh9jQTo3ooWMlWdiQYH3/hb1VI=
  app: planningtask
  on:
    repo: Gescosolution/Planning-task
