language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Cb7jh4dsTKFSQA0AGd+RfMnfJJuKTg+3G4K3XbRMrCZyFWZlW6b/tQFp6LGiKAMzNSZxQCHhTiE9PJfNBc8Nb4h0cwRpVgjLbnQ53eTFF76Yjm4mLtH3GH7Ugj0kBIIB8kpgPJzrbh2HppI67XdKx8cbz8OrXFcE26BQwocsi8L8vx5yJlKCHZEi8PoDhUjhWufYsTzIIXqKdPL4AZ5VfMgunITeR0Ws7YzV4Hdb/7QIMHXh2ndaZqegKuuGCOYinmnDov/p4e0S4TE19l6jX8hxmHDfL8BINKtvu3UnTZguWVF/vEfRAxmXB8ac1JnUuvE4h5mhLvpFiAjrY0qywdhpmEFPRYUk3YvRku/MWLjt6smI7a+v9HmdxAilHHp/thX4tO0uUJrnTu4nLPJ0ZbxvMjiNJSwxtMwgZAIDKIX3Gsm4/Hc2cEzAQsErg55uhVPUlJhBYgqOUUM49ANZ/G2D9Ugg0eHe4FAW1yeF7ek5dcsgv+BSJFaL5JLkw0aSl3KMR687eJNqg3XlcwLHyedLnaFY1AT5i3wdQquCGjRIyE8fY33/8YRmO/Uop5piWAZcXc8t6KlsBZz2e7T8qUmFkV3eIRCuIZKwktrRiFmHv983/J8fvUd6sa6TWuvFla2U4v4+H7GKq8MFcuq2dzBdI/ru8y2IndlXzZSsI8Y=
  app: taskplanning
  on:
    repo: robermorji/Planning-task
