language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: fZizLD/+b6qJuMLlh7ZL8eHD0NPzUuP981SUm99DF4p23umNGDsuKtC2HpiiIhiJ0ZbqMOH8AwtsAZNe40Qa7vOBpvqArRsZjkSl6Ub09Itgfr5uEDLwUI2GIxDQywQWoZafFlF14BVdDA1ZwO4NXjmQEQm+1NfG1oPBItcuI9CJJgE92a2jOqm5UysvnEHjM160XunekDUADmDmbezuIF6Bx9mMmuVx4xtrx+QM79ucwQg5ff2L1chJ5PdTc8zDwPGJrQ+ZFP47QoNWrhILpHvsI2T3HZejewja2uud9cx3GanfJ2BgBwyY/NDUQwdx311cSGQF/6ooGDJZgvSAMbtDXNz+/sWjBGxXO14gXf3XKBq3v+M8YbQVHOmguDsw7zEuXmg/a97QUJtkrOfqfeM/9ba0600czMLqrisy4Hw/S0HrnSu+tAjXY2xIMTHlpsPk0XFxv4fz1y7QpWaczrxV4W0JN3uv2sdlzrYVirUgRtn0fn/2r9pxGvG7uo97uS87b1ffPlayzgacPe1jV4Qk41JV5UVaAmeQMQXtJQncj0N5UTe23ExTy0gR9SBlgy/d/PDy0OYDIOLJpyRzjJkWKBOTgpZsF6o22KNiGTodbg46GNuzzXmSU3GDMmLUQKQZ3tkvay9tNnuXpltC+2Y/LvWFqmGcCdEXYnxLYm0=
  app: planni
  on:
    repo: Gescosolution/Planning-task
