language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: T274LQjQ6mA1z9w2NAHPNLIHBLtDrUYFN2GORqhZL32ga6vGwylhcpQqImlPZSuz6BeIba3mxELr+5hGnADhCPh+keMjx2H719OBb1IuHFbraVRdg7OF40E+9zKzkKrRf+GJNBtSzuxj/JPYiNV2iFST6mIZDp770mATqn473O6UO+Y0SJi9nIwBOVYNUASABClA/e4GcYQSqzrQJoXL/fhhw1YcxdqRJ0fp7mAdyRK4M53C8ekoqCg45lhmRu5IWOFwlKahqxh3fpeTeaX3HS7DUn3mc6U/Pmx4GkwG/SQPWMB6LR13VGYkJU8eA/6oYb1PoBfnH6WjzvjqpviwooGl+glXKg4064nGB938+9+u8K5g4QMolqvTlOT9HvGJO1daR4cLC4rLzVx5t7fSFZ58zHPBTfLKmB4aBJRjgCRep7gaQeDKPBPNFBoNGvFp0vO9yhwEL54OgKKAv1AY4NrsltmARSj8bdjdmornL8IsTSqSugEvU4/Hp81hBGLZC136o6M11iftwWEbdAw0bjWvloLktikNVM/wX7MhfwAWxFc8dq1s39CSvyUsbmtk89jlRRzUyTVqeT3o3wlMumwYJDxQzT6gUkgHnw9yqJB6RIiQ77UMEgp1CjZhoiwb0fd6mpHpXZpp7HnELHRU6GZ0/HX1WTZvWkR0FW14DMY=
  app: planningtask
  on:
    repo: Gescosolution/Planning-task
