# language setting
language: node_js

# version numbers, testing against two versions of node
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

services:
  - mongodb

deploy:
  provider: heroku
  api_key:
    secure: "c690df36-77c0-49ff-aad7-f57fb9faf0bf"
    app: planningtask
